POST http://127.0.0.1:6380/mint-next-and-add-auth-methods
Content-Type: application/json
api-key: your-api-key-value

{
    "keyType": 2,
    "permittedAuthMethodTypes": [2],
    "permittedAuthMethodIds": ["0x170d13600caea2933912f39a0334eca3d22e472be203f937c4bad0213d92ed71"],
    "permittedAuthMethodPubkeys": ["0x"],
    "permittedAuthMethodScopes": [[1]],
    "addPkpEthAddressAsPermittedAddress": true,
    "sendPkpToItself": true
}
